field: 74eb36ae-7a26-4e7d-b454-990ec52617f0 # Builder: Content
fieldLayouts:
  b5f39594-4dfb-477b-a358-ea2dac368b7b:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 9a8fffce-3c28-4326-8f7a-e31d2f6cc04b # Section Background Color
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 483ce826-3abf-48ac-8c95-5114bda99f30
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 74b87138-1475-47c2-a9dd-63baa78dd5f5 # Space Between Blocks
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 16c62a98-e675-40ee-a4d0-8ca2543ed5de
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: aa7883a4-2cce-4316-85f3-ec6ea59402ec # Section Padding Vertical
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d2acb96f-9f12-4449-ad76-d024ad3d28ab
            userCondition: null
            warning: null
            width: 50
        name: Content
        uid: 5cb029e3-a009-451e-8ab8-a2a2dec9a3f5
        userCondition: null
fields:
  9a8fffce-3c28-4326-8f7a-e31d2f6cc04b: # Section Background Color
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: sectionBackgroundColor
    instructions: null
    name: 'Section Background Color'
    searchable: false
    settings:
      cachedOptions: true
      element: null
      genError: ''
      json: ''
      multi: false
      template: _super-dynamic-fields/background-color-section.json
      templateData: ''
    translationKeyFormat: null
    translationMethod: none
    type: amici\SuperDynamicFields\fields\SueprDynamicDropdownField
  74b87138-1475-47c2-a9dd-63baa78dd5f5: # Space Between Blocks
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: spaceBetweenBlocks
    instructions: null
    name: 'Space Between Blocks'
    searchable: false
    settings:
      cachedOptions: true
      element: null
      genError: ''
      json: ''
      multi: false
      template: _super-dynamic-fields/spacing-between-y.json
      templateData: ''
    translationKeyFormat: null
    translationMethod: none
    type: amici\SuperDynamicFields\fields\SueprDynamicDropdownField
  aa7883a4-2cce-4316-85f3-ec6ea59402ec: # Section Padding Vertical
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: sectionPaddingVertical
    instructions: null
    name: 'Section Padding Vertical'
    searchable: false
    settings:
      cachedOptions: true
      element: null
      genError: ''
      json: ''
      multi: false
      template: _super-dynamic-fields/spacing-padding-vertical.json
      templateData: ''
    translationKeyFormat: null
    translationMethod: none
    type: amici\SuperDynamicFields\fields\SueprDynamicDropdownField
handle: blockSection
name: Section
sortOrder: 1
