color: green
fieldLayouts:
  e22d570c-156e-4591-a91a-2af67c7ed22b:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-09-04T21:50:53+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 21abcfb8-eef7-47d7-b8d4-c07dbb0e5c1b
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-05T21:01:42+00:00'
            elementCondition: null
            fieldUid: e884a8f9-92f0-48b3-a7e8-a6d95f47f6df # Text Multi
            handle: quote
            includeInCards: true
            instructions: null
            label: Quote
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bbdc2ef0-cb88-420a-86a7-c25831e21b77
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-05T19:57:29+00:00'
            elementCondition: null
            fieldUid: edfcb398-ef78-43ec-9434-d6405da2886e # Text Single
            handle: source
            includeInCards: false
            instructions: null
            label: Source
            providesThumbs: false
            required: false
            tip: 'Use this if you don''t need a linked source.'
            type: craft\fieldlayoutelements\CustomField
            uid: 6be08230-3b3c-4ebc-8a13-0511551e439d
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-04T21:56:19+00:00'
            elementCondition: null
            fieldUid: a3f76ec3-252e-4be6-8178-8f6b54acce19 # Link
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: 'Use this if you need a linked source.'
            type: craft\fieldlayoutelements\CustomField
            uid: b5ae7482-d980-4d0a-9878-2924a100da73
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 8e061a5e-d78f-48e7-b026-09c9f9a49a67
        userCondition: null
handle: blockQuote
hasTitleField: false
icon: quote-right
name: Quote
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
