color: yellow
fieldLayouts:
  a4335b2d-af34-4544-b20a-e4a928a3693c:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-09-04T21:50:31+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 20b6ecbd-8965-418d-8577-a28920043388
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-05T06:05:04+00:00'
            elementCondition: null
            fieldUid: aa7883a4-2cce-4316-85f3-ec6ea59402ec # Spacing
            handle: height
            includeInCards: true
            instructions: null
            label: Height
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d7ad081b-2e70-4b66-b2e3-1a730fcd83d7
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 1ce6448e-436d-4f3c-b18e-d4b338f00b99
        userCondition: null
handle: blockSpacer
hasTitleField: false
icon: rectangle
name: Spacer
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
