color: cyan
fieldLayouts:
  1abefa28-ba0b-4e7e-be2b-12835562bb01:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-09-04T22:01:40+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 7c34b185-3f40-46f6-a613-5417ba6cf832
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-04T19:47:47+00:00'
            elementCondition: null
            fieldUid: 63bd200d-3882-4788-a8ba-528452521d6c # Video Provider
            handle: null
            includeInCards: true
            instructions: null
            label: 'Video Provider'
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 61617279-3f13-4142-9007-28c5defd3157
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-09-04T22:05:07+00:00'
            elementCondition: null
            fieldUid: edfcb398-ef78-43ec-9434-d6405da2886e # Text Single
            handle: videoId
            includeInCards: false
            instructions: null
            label: 'Video ID'
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 04a6c16d-18b1-4afd-8a03-65971db6bbe8
            userCondition: null
            warning: null
            width: 50
        name: Content
        uid: bb2df4f8-8532-459f-ae5f-12b9013d58c0
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-09-04T22:05:07+00:00'
            elementCondition: null
            fieldUid: 31947efb-fa8c-473c-9b01-bd36c8d70b68 # Lightswitch OFF
            handle: autoplay
            includeInCards: false
            instructions: null
            label: Autoplay
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 262f674b-bfd8-4eed-9a47-76f110e7d909
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-09-04T22:05:07+00:00'
            elementCondition: null
            fieldUid: 31947efb-fa8c-473c-9b01-bd36c8d70b68 # Lightswitch OFF
            handle: loop
            includeInCards: false
            instructions: null
            label: Loop
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bda8d9c0-76a8-4405-b0c8-19b8d90a4c87
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-09-04T19:47:47+00:00'
            elementCondition: null
            fieldUid: 68109da0-245f-4b21-b040-b7f4385e618e
            handle: null
            includeInCards: false
            instructions: null
            label: 'Video Width'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6b9c294a-c00e-4b45-b0e5-c0ff793155ac
            userCondition: null
            warning: null
            width: 50
        name: Settings
        uid: 90b44b85-ac66-4f2d-b2a1-d39f9aa12ec8
        userCondition: null
handle: blockVideo
hasTitleField: false
icon: play
name: Video
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
