color: cyan
fieldLayouts:
  6c449cd7-ebc2-4ce6-be61-1e8c90cb176b:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-09-04T21:22:12+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: efef2748-d17e-44ad-adbe-2f2f8504dbc3
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-04T19:47:47+00:00'
            elementCondition: null
            fieldUid: 74c3cd4f-b565-4fb4-879e-72022774f93c # Images View Mode
            handle: null
            includeInCards: true
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 11e9d4b4-edcc-4533-b7a1-8b07c6602017
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-04T19:47:47+00:00'
            elementCondition: null
            fieldUid: 75195ab8-b7c4-4dca-b807-ef8a042ef5a9 # Images
            handle: null
            includeInCards: true
            instructions: null
            label: null
            providesThumbs: true
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d10b279e-4bce-49cf-90fd-0a2fae06d537
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 56042e3e-7a7b-4a4c-9222-63e004682c9b
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-09-04T19:47:47+00:00'
            elementCondition: null
            fieldUid: 62883121-63a2-4e5c-a6f3-4855cf64df2c # Image Ratio
            handle: null
            includeInCards: false
            instructions: null
            label: 'Image Ratio'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 721a9d99-a7c1-4462-b772-b18fadab09e8
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-09-04T21:26:43+00:00'
            elementCondition: null
            fieldUid: 31947efb-fa8c-473c-9b01-bd36c8d70b68 # Lightswitch OFF
            handle: showCaption
            includeInCards: false
            instructions: null
            label: 'Show Caption'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4c0afd85-25ca-4a2d-953e-ffdb72188d7a
            userCondition: null
            warning: null
            width: 50
        name: Settings
        uid: 18bed5b9-f49a-469d-b58d-0258602e7466
        userCondition: null
handle: blockImages
hasTitleField: false
icon: images
name: Images
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
