color: cyan
fieldLayouts:
  58ddc97d-9694-4104-a136-b6344987e1b6:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-09-04T20:16:46+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 382b79d3-4ec7-4960-b1e4-01ae81fda007
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-04T19:47:47+00:00'
            elementCondition: null
            fieldUid: b81cb731-dd6f-4055-9c6d-2f076a727a27 # Image
            handle: null
            includeInCards: false
            instructions: null
            label: Image
            providesThumbs: true
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0cd02812-349c-46d5-a4b7-57700a221566
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 5e8a312e-45d0-491c-924d-84d96af3b270
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-09-04T19:47:47+00:00'
            elementCondition: null
            fieldUid: 62883121-63a2-4e5c-a6f3-4855cf64df2c # Image Ratio
            handle: null
            includeInCards: false
            instructions: null
            label: 'Image Ratio'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b0fb63ad-8f84-4caf-a7b6-c0e44deeae12
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-09-04T19:47:47+00:00'
            elementCondition: null
            fieldUid: 1be86da8-5273-40c6-ba88-718f5c32a6c3
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 744a7c6f-6d25-4c12-8d70-9a8752b5f5f6
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-09-04T21:45:26+00:00'
            elementCondition: null
            fieldUid: 31947efb-fa8c-473c-9b01-bd36c8d70b68 # Lightswitch OFF
            handle: showCaption
            includeInCards: true
            instructions: null
            label: 'Show caption'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bf115a81-cfa7-41f1-9c22-72b7b5939e55
            userCondition: null
            warning: null
            width: 50
        name: Settings
        uid: 95b16a67-6431-4b73-9fe2-8cc156d078ee
        userCondition: null
handle: blockImage
hasTitleField: false
icon: image
name: Image
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
