color: green
fieldLayouts:
  410c9682-a3f7-4475-9013-0453aac4635d:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-09-04T20:21:02+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 54c40c44-8ca8-4511-b03a-e5e0f6ecd206
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-04T19:47:47+00:00'
            elementCondition: null
            fieldUid: be45c3e2-5e9f-491e-a000-94d95c4fa20b # Code Snippet
            handle: null
            includeInCards: false
            instructions: null
            label: Snippet
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d0187af9-ab3b-48cf-9fa9-8cfb76e48a9e
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-04T20:49:32+00:00'
            elementCondition: null
            fieldUid: edfcb398-ef78-43ec-9434-d6405da2886e # Text Single
            handle: codeSnippetName
            includeInCards: true
            instructions: null
            label: 'Code Snippet Name'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e786a1d6-f10b-45b2-804f-06f9ae8ddabf
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-09-04T20:24:42+00:00'
            elementCondition: null
            fieldUid: 31947efb-fa8c-473c-9b01-bd36c8d70b68 # Lightswitch OFF
            handle: collapsed
            includeInCards: false
            instructions: null
            label: Collapsed
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6c1d2950-2c47-4f4a-b714-7a3cb88712cf
            userCondition: null
            warning: null
            width: 50
        name: Content
        uid: c033e8a9-eab3-4bd0-bea5-4a8d2dcf5ad3
        userCondition: null
handle: blockCode
hasTitleField: false
icon: code
name: Code
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
