color: green
fieldLayouts:
  653f85bd-d164-45dc-a6ee-74e19fcc7b3a:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-09-04T23:21:15+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 94eb125a-d1ca-4b86-bbd3-03c76a568398
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-04T23:22:44+00:00'
            elementCondition: null
            fieldUid: c8a9d048-8e52-42a3-8e8a-44633a838802 # Links
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6de2b09f-32e0-430f-ab1d-f75ce0c64de7
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 29a34be1-ab6b-4e29-971e-d09803a47cfa
        userCondition: null
handle: blockLinks
hasTitleField: false
icon: link
name: Links
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
