color: green
fieldLayouts:
  7b6ace88-ae82-4caf-afe4-1650ce6e7ce3:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-09-04T20:16:52+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 7dfb8abd-71de-4d92-8b62-13b7a50ea2a6
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-04T22:02:29+00:00'
            elementCondition: null
            fieldUid: 9add7508-89cd-4b19-b8e5-f6173a4ec371 # Rich Text
            handle: null
            includeInCards: true
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 243140b3-d692-4031-b56b-8a51521c3fae
            userCondition: null
            warning: null
            width: 100
        name: Text
        uid: a7ac4d85-057b-421c-a16b-b382da491a30
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-09-04T19:47:47+00:00'
            elementCondition: null
            fieldUid: b81cb731-dd6f-4055-9c6d-2f076a727a27 # Image
            handle: null
            includeInCards: false
            instructions: null
            label: Image
            providesThumbs: true
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ab6dd79a-0d9c-4799-860a-01a7c242ba68
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-09-04T19:47:47+00:00'
            elementCondition: null
            fieldUid: 62883121-63a2-4e5c-a6f3-4855cf64df2c # Image Ratio
            handle: null
            includeInCards: false
            instructions: null
            label: 'Image Ratio'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 04337482-6861-47b4-8a21-cd4447d746ab
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-09-04T19:47:47+00:00'
            elementCondition: null
            fieldUid: 210de09a-f6c8-42dd-b4d6-c1c00e7d0b82 # Image Position
            handle: null
            includeInCards: false
            instructions: null
            label: 'Image Position'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1ce2335a-ddf7-4a2f-a788-0c629ecec74b
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-09-04T22:02:29+00:00'
            elementCondition: null
            fieldUid: 31947efb-fa8c-473c-9b01-bd36c8d70b68 # Lightswitch OFF
            handle: showCaption
            includeInCards: false
            instructions: null
            label: 'Show Caption'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b5c87ad3-30a4-42d6-bf64-9fd21c1e7259
            userCondition: null
            warning: null
            width: 50
        name: Image
        uid: 7931c967-9547-46fa-99e4-270c687a7cb3
        userCondition: null
handle: blockTextImage
hasTitleField: false
icon: table-columns
name: 'Text : Image'
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
