color: red
fieldLayouts:
  39b9e1a8-a9fe-46a4-aad9-966389ae8743:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-09-04T19:47:47+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: dd63bc42-f4e0-4ecd-a5c7-288a5e7946b2
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-04T22:19:05+00:00'
            elementCondition: null
            fieldUid: edfcb398-ef78-43ec-9434-d6405da2886e # Text Single
            handle: customTitle
            includeInCards: true
            instructions: null
            label: 'Custom Title'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 51e17a0f-d990-4fc4-b066-fc90727cabee
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-04T22:19:05+00:00'
            elementCondition: null
            fieldUid: 5af0a821-fa33-490a-9439-3193f439dd06 # Rich Text Simple
            handle: description
            includeInCards: true
            instructions: null
            label: Description
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cfc6688b-27f5-4967-9f56-17c7e81901d2
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-04T22:19:05+00:00'
            elementCondition: null
            fieldUid: b81cb731-dd6f-4055-9c6d-2f076a727a27 # Image
            handle: null
            includeInCards: true
            instructions: null
            label: null
            providesThumbs: true
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f78c1709-24f1-4f7a-b5b1-da663254f24b
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 19f2f3ee-8dd2-4cb7-a283-067d9468d7a5
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-09-04T19:47:47+00:00'
            elementCondition: null
            fieldUid: d29e8520-ab62-4c8f-bda2-61868797c1ca # SEOmatic
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ee0f87a2-09fe-40be-ae32-32d65f24fb3f
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: 19225308-28cc-46b1-8075-f4dc542c6c81
        userCondition: null
handle: entryListNews
hasTitleField: true
icon: memo
name: '_List: News'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
