fieldLayouts:
  be62de4f-cc21-4603-aab3-8623d43b46ad:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 11f6a034-44e7-434e-8035-8dbb7423fbb3
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 1516a801-6243-468d-b8e2-479085458faa # Text: Custom Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8930f333-8bbf-4d59-8b78-632ff5d5e709
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 45510f13-91d2-479f-9ff2-68dd09ab6643 # Text: Entry Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 71881212-33f8-4422-b14e-bd3a2f053d1f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0dc851b0-a289-4c50-be8d-0c055b270ee8 # Asset: Entry Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 73d71fe2-8149-4c20-8744-5dfda0d2e742
            userCondition: null
            warning: null
            width: 100
        name: Entry
        uid: 3314e7a8-7edd-461d-bdad-5a093d526ddd
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 74eb36ae-7a26-4e7d-b454-990ec52617f0 # Builder: Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6d136a36-b3d5-4fd6-acb4-ab5de0228a26
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: baee5fce-39b4-49ec-8668-707dd127397f
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: d29e8520-ab62-4c8f-bda2-61868797c1ca # SEO: SEOmatic
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6fba6047-0faa-41d1-8404-16a9d9bfa56c
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: c7d4e6c6-adcf-499a-97b1-2006cda02e10
        userCondition: null
handle: home
hasTitleField: false
name: Home
section: 5d0f7961-203c-4008-a55a-6a7d35e7a37a # Home
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
