css: null
js: null
name: Default
toolbar:
  - alignment
  - heading
  - style
  - '|'
  - bold
  - italic
  - underline
  - strikethrough
  - subscript
  - superscript
  - '|'
  - link
  - bulletedList
  - numberedList
  - code
  - '|'
  - codeBlock
  - insertTable
