altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  1c050c97-46a7-44da-8b07-841009d282f4:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-09-04T19:47:47+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 0d54794f-2cbf-4dce-9dd1-0375444002b9
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-09-04T22:40:12+00:00'
            elementCondition: null
            fieldUid: edfcb398-ef78-43ec-9434-d6405da2886e # Text Single
            handle: customTitle
            includeInCards: true
            instructions: null
            label: 'Custom Title'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 04b3690b-c1ac-4adb-a336-aafdb037d243
            userCondition: null
            warning: null
            width: 100
          -
            attribute: alt
            class: null
            cols: null
            dateAdded: '2024-09-04T19:47:47+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: true
            instructions: null
            label: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: true
            required: false
            rows: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AltField
            uid: 5336157c-649a-4a3b-b74f-b8313d13d9fe
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-04T22:40:12+00:00'
            elementCondition: null
            fieldUid: 5af0a821-fa33-490a-9439-3193f439dd06 # Rich Text Simple
            handle: caption
            includeInCards: false
            instructions: null
            label: Caption
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f22df577-47b2-4226-92eb-175d23a6af2b
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-04T22:40:12+00:00'
            elementCondition: null
            fieldUid: a3f76ec3-252e-4be6-8178-8f6b54acce19 # Link
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e25489fd-2750-4bf0-b0b4-94ef99377eb1
            userCondition: null
            warning: null
            width: 50
        name: Content
        uid: 7fa2cead-3f59-4c5b-8562-8ee83d4acf7b
        userCondition: null
fs: assets
handle: users
name: Users
sortOrder: 4
subpath: users
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: transforms
transformSubpath: craft/users
