columnSuffix: null
handle: lightswitchOff
instructions: null
name: 'Lightswitch OFF'
searchable: true
settings:
  default: false
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
