columnSuffix: null
handle: linkStyle
instructions: null
name: 'Link Style'
searchable: false
settings:
  options:
    -
      __assoc__:
        -
          - label
          - Primary
        -
          - value
          - primary
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - Secondary
        -
          - value
          - secondary
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Outlined
        -
          - value
          - outlined
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
