columnSuffix: null
handle: sectionBackgroundColor
instructions: null
name: 'Builder: Content - Section - Section Background Color'
searchable: false
settings:
  options:
    -
      __assoc__:
        -
          - label
          - Transparent
        -
          - value
          - transparent
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - 'Light Gray'
        -
          - value
          - light-gray
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
