columnSuffix: ibratpfs
contentColumnType: text
fieldGroup: dfb88745-e0f0-4c67-9781-f72dad33bf65 # SEO
handle: seoSEOmatic
instructions: null
name: 'SEO: SEOmatic'
searchable: false
settings:
  elementDisplayPreviewType: google
  facebookEnabledFields: ''
  facebookTabEnabled: ''
  generalEnabledFields:
    - seoPreview
    - mainEntityOfPage
    - seoTitle
    - seoDescription
    - seoKeywords
    - seoImage
    - robots
    - canonicalUrl
  generalTabEnabled: '1'
  sitemapEnabledFields: ''
  sitemapTabEnabled: ''
  twitterEnabledFields: ''
  twitterTabEnabled: ''
translationKeyFormat: null
translationMethod: none
type: nystudio107\seomatic\fields\SeoSettings
