columnSuffix: twbwiyps
contentColumnType: text
fieldGroup: 4267733c-fa2b-45f5-a3b6-8b56a1c56dc4 # Text
handle: textCustomTitle
instructions: null
name: 'Text: Custom Title'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
