columnSuffix: qhlkmili
contentColumnType: text
fieldGroup: 4267733c-fa2b-45f5-a3b6-8b56a1c56dc4 # Text
handle: textRichTextDefault
instructions: null
name: 'Text: Rich Text Default'
searchable: true
settings:
  availableTransforms: ''
  availableVolumes: ''
  ckeConfig: 6f4a3e01-23de-4313-8109-00a430317d11 # Rich Text Default
  columnType: text
  defaultTransform: null
  enableSourceEditingForNonAdmins: false
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: true
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
