columnSuffix: xmuynimp
contentColumnType: string(255)
fieldGroup: 4267733c-fa2b-45f5-a3b6-8b56a1c56dc4 # Text
handle: textSourceUrl
instructions: null
name: 'Text: Source Url'
searchable: true
settings:
  maxLength: 255
  types:
    - url
translationKeyFormat: null
translationMethod: none
type: craft\fields\Url
