dateModified: 1725479328
elementSources:
  craft\elements\Asset:
    -
      key: 'volume:6c5fc0dd-cf56-48d8-8af8-88abe763b970' # Files
      type: native
    -
      disabled: false
      key: 'volume:f1b38495-8096-48fa-9b78-0da345e3295c' # Images
      tableAttributes:
        - filename
        - size
        - dateModified
        - uploader
        - link
        - imageSize
      type: native
    -
      disabled: false
      key: 'volume:77c74b5c-6bbb-41a7-b166-c6b158a3cc7f' # Template Images
      tableAttributes:
        - filename
        - size
        - dateModified
        - uploader
        - link
        - imageSize
      type: native
    -
      key: 'volume:8dda1580-81a2-49f5-9dd2-ed1e2eb03fc6' # Users
      type: native
    -
      key: 'folder:c8e15363-b103-4fd2-b6e4-097752fa2cef'
      type: native
email:
  fromEmail: $SYSTEM_MAIL
  fromName: $SITE_NAME
  replyToEmail: $REPLY_MAIL
  template: null
  transportSettings:
    command: ''
  transportType: craft\mail\transportadapters\Sendmail
fs:
  files:
    hasUrls: true
    name: Files
    settings:
      path: '@webroot/assets/files'
    type: craft\fs\Local
    url: '@assetsUrl/files/'
  images:
    hasUrls: true
    name: Images
    settings:
      path: '@webroot/assets/images'
    type: craft\fs\Local
    url: '@assetsUrl/images/'
  templateImages:
    hasUrls: true
    name: 'Template Images'
    settings:
      path: '@webroot/assets/templateImages'
    type: craft\fs\Local
    url: '@assetsUrl/templateImages/'
  transforms:
    hasUrls: true
    name: Transforms
    settings:
      path: '@webroot/assets/transforms'
    type: craft\fs\Local
    url: '@assetsUrl/transforms/'
  users:
    hasUrls: true
    name: Users
    settings:
      path: '@webroot/assets/users'
    type: craft\fs\Local
    url: '@assetsUrl/users/'
meta:
  __names__:
    0dc851b0-a289-4c50-be8d-0c055b270ee8: 'Asset: Entry Image' # Asset: Entry Image
    1c94bbf7-46b0-46e4-a699-b4eef42994a0: 'Text: Editor Simple' # Text: Editor Simple
    2bc1feee-cfc8-48ee-bace-f101e7f41ac9: Default # Default
    2f642060-4792-41cb-a427-083aabeba231: 'Page Content Builder' # Page Content Builder
    5d0f7961-203c-4008-a55a-6a7d35e7a37a: Home # Home
    6c5fc0dd-cf56-48d8-8af8-88abe763b970: Files # Files
    6d94dcc4-6ec1-45b4-8c86-e53cee842b11: 'Page News' # Page News
    6f4a3e01-23de-4313-8109-00a430317d11: 'Rich Text Default' # Rich Text Default
    7eb1a718-0679-4fda-b656-9bfdf55a2025: 'Navigation Main' # Navigation Main
    8ced5be5-13b2-483f-8db9-aab9757aad21: Error # Error
    8d272b11-c1b4-4fc3-95c8-9d94fa513795: 'Text: Links' # Text: Links
    8dda1580-81a2-49f5-9dd2-ed1e2eb03fc6: Users # Users
    63e3914d-ee70-44c2-9dc3-91551f47c54f: 'Text: Editor Default' # Text: Editor Default
    74eb36ae-7a26-4e7d-b454-990ec52617f0: 'Builder: Content' # Builder: Content
    77c74b5c-6bbb-41a7-b166-c6b158a3cc7f: 'Template Images' # Template Images
    81d0ea50-f7e1-4eff-8138-2a06ffbfae86: Home # Home
    419ebfbb-8723-48db-ae89-10adf52cdf11: 'Text: Source' # Text: Source
    1516a801-6243-468d-b8e2-479085458faa: 'Text: Title Overwrite' # Text: Title Overwrite
    3547e7b4-f3fb-4cf4-9d29-9f12dfa94594: News # News
    8153a2df-373f-4aac-9a92-d52292c9f1aa: Baukasten # Baukasten
    8780cb03-c9ea-4482-ab85-3e541453b50f: 'Text: Source Url' # Text: Source Url
    9005a655-4d9f-46b4-8c33-aadba34b6112: 'Social Sharing Facebook' # Social Sharing Facebook
    45510f13-91d2-479f-9ff2-68dd09ab6643: 'Text: Description' # Text: Description
    644167c0-ab2a-4f9d-9b2b-09f5a6556ef3: 'Public Schema' # Public Schema
    aac37142-e533-49aa-8665-b8cc6360e98b: 'Text: Caption' # Text: Caption
    b0207f48-be48-49ab-a759-1ff51f232df3: Pages # Pages
    d29e8520-ab62-4c8f-bda2-61868797c1ca: 'SEO: SEOmatic' # SEO: SEOmatic
    e8b10d27-be46-4108-9bf5-3a8711280165: 'Rich Text Simple' # Rich Text Simple
    e5172a18-ed16-4229-89ca-fc0dc776597a: 'Error Pages' # Error Pages
    f1b38495-8096-48fa-9b78-0da345e3295c: Images # Images
    f4959e03-fec0-4b1c-887e-5301a5f66742: 'Social Sharing Twitter' # Social Sharing Twitter
    fb701216-3e80-4e6d-99d4-2e5f70561e22: 'News Default' # News Default
plugins:
  blitz:
    edition: standard
    enabled: true
    licenseKey: $PLUGIN_BLITZ
    schemaVersion: 5.7.0.1
    settings:
      integrations:
        - putyourlightson\blitz\drivers\integrations\CommerceIntegration
  blur-hash:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  ckeditor:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0.0
  codefield:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  cp-css:
    edition: standard
    enabled: true
    schemaVersion: 2.0.0
    settings:
      additionalCss: ''
      cssFile: /dist/css/controlPanelCss.css
  cp-field-inspect:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  elements-panel:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  empty-coalesce:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  hyper:
    edition: standard
    enabled: true
    licenseKey: $PLUGIN_HYPER
    schemaVersion: 1.0.0
  imager-x:
    edition: pro
    enabled: true
    licenseKey: $PLUGIN_IMAGERX
    schemaVersion: 4.0.0
  navigation:
    edition: standard
    enabled: true
    licenseKey: $PLUGIN_NAVIGATION
    schemaVersion: 2.1.0
  seomatic:
    edition: standard
    enabled: true
    licenseKey: $PLUGIN_SEOMATIC
    schemaVersion: 3.0.12
    settings:
      addHrefLang: true
      addPaginatedHreflang: true
      addXDefaultHrefLang: true
      cpTitlePrefix: '⚙ '
      cspNonce: ''
      cspScriptSrcPolicies:
        -
          __assoc__:
            -
              - policy
              - '''self'''
      devModeCpTitlePrefix: '&#x1f6a7;⚙ '
      devModeTitlePrefix: '&#x1f6a7; '
      displayAnalysisSidebar: true
      displayPreviewSidebar: true
      enableJsonLdEndpoint: false
      enableMetaContainerEndpoint: false
      enableSeoFileLinkEndpoint: false
      environment: local
      generatorEnabled: true
      headersEnabled: true
      includeHomepageInBreadcrumbs: true
      lowercaseCanonicalUrl: '1'
      manuallySetEnvironment: false
      maxDescriptionLength: 155
      maxTitleLength: 70
      metaCacheDuration: 'null'
      pluginName: SEOmatic
      regenerateSitemapsAutomatically: true
      renderEnabled: true
      separatorChar: '|'
      sidebarDisplayPreviewTypes:
        - google
        - twitter
        - facebook
      siteGroupsSeparate: '1'
      siteUrlOverride: ''
      sitemapsEnabled: true
      socialMediaPreviewTarget: true
      submitSitemaps: true
      truncateDescriptionTags: '1'
      truncateTitleTags: '1'
  sprig:
    edition: standard
    enabled: true
    schemaVersion: 1.0.1
  vite:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: pro
  live: true
  name: Baukasten
  retryDuration: null
  schemaVersion: 5.3.0.2
  timeZone: Europe/Berlin
users:
  allowPublicRegistration: false
  deactivateByDefault: false
  defaultGroup: ''
  photoSubpath: '{username}'
  photoVolumeUid: 8dda1580-81a2-49f5-9dd2-ed1e2eb03fc6 # Users
  requireEmailVerification: true
  validateOnPublicRegistration: false
